site_name: SERVER GEESE

theme:
  name: material
  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 


        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - blog
  - tags


nav:
  - Home: index.md
  - Game Development:
      - Unreal Engine 5: gamedev/ue5.md
      - Debt Is Eternal (DIE): gamedev/die-project.md
      - Visuals & UI: gamedev/visuals.md
      - Multiplayer:
          - Overview: gamedev/multiplayer/overview.md
          - GameLift: gamedev/multiplayer/gamelift.md
  - DevOps & Cloud:
      - Overview: devops/index.md
      - Terraform:
          - EC2 + RDS: devops/terraform/ec2-nginx-rds.md
      - AWS:
          - IAM Pitfalls: devops/aws/iam-pitfalls.md
      - Automation:
          - Golang Scripts: devops/automation/golang-scripts.md
          - GitHub Actions: devops/automation/github-actions.md

